Numpy - это библиотека python для удобной и быстрой работой над операциями с матрицами

In [2]:
import numpy as np

dim - ранг массива (например, двухмерный массив имеет второй ранг)
dtype - задает тип данных в матрице
shape - размер массива (кортеж), можно передавать как с круглыми, так и с квадратными скобками
(reshape применяется только если после операции кол-во элементов в матрице будет равно изначальному)
size - кол-во элементов в массиве
(не безопасная версия shape, ему плевать на кол-во элементовв, он либо их урежет, либо добавит нули в недостающее место)
axis - оси матрицы (axis = 0 это столбцы, axis = 1, это строки)

In [3]:
matrix = np.array([2, 4, 5], dtype=int) #dtype устанавливает тип данных в матрице
matrix = np.arange(10, 20) # как range

matrix_1d = np.arange(8)
matrix_2d = np.arange(8).reshape(2, 4)
matrix_3d = np.arange(12).reshape(3, 2, 2)
matrix_4d = np.arange(96).reshape(2, 3, 4, 4) #четырех мерная матрица

#print(matrix_4d, end='\n\n\n')

np.ones((2, 2)) #создает матрицу из еденичек, размером shape
np.zeros((1, 10))
np.empty((1, 1))
a = np.full([1, 3, 4], 7)

np.zeros_like(matrix_2d) #создает матрицу из нулей с размером заданной матрицы
np.ones_like(matrix_1d)
np.full_like(matrix_3d, 3)

b = np.resize(matrix_3d, (3, 2))

#print(a)
#print(b)
#print(matrix_3d)

# Свойства массивов

In [4]:
matrix_4d.ndim # возвращает кол-во осей
matrix_3d.size # возвращает кол-во элементов
matrix_4d.shape # возвращает кортеж, на котором показывает, сколько элементов лежит на каждой из оси

(2, 3, 4, 4)

# Преобразования матриц

In [5]:
np.mat([1, 2, 3, 4, 4]) # преобразует переданный массив в двумерную матрицу (обратите внимание на скобочки после трансформации- их стало 2))
np.diag([1, 2, 3]) # преобразует список в диагональную матрицу
np.diag(matrix_2d) # но если в нее передать матрицу, то она скажет что лежит на нее диагонали
np.diagflat(matrix_2d) # превращает любой (даже двухмерный) массив в диагональную матрицу
np.eye(4) # еденицы в качестве диагональной матрицы, где переданное число- длина диагонали по элементам
np.eye(2, 4) # но можно задать и кортеж

np.tri(3) #вернет нижнюю треугольную матрицу
# np.tri(3, 10)
np.tril(matrix_2d) #вернет tri из переданной матрицы (а остальное в нулях)
np.triu(matrix_3d) #вернет верхнюю треуг. матрицу

matrix_3d.reshape(1, -1) # -1, что бы не считать до конца
matrix_2d.shape = (-1, 2)
# print(matrix_2d)

matrix_2d[2, 1] = 100
# print(matrix_2d)
matrix_3d[2] = 99
# print(matrix_3d)

# Когда мы присваиваем матрице с индексом какое то значение, то оно присваивается КАЖДОМУ ЭЛЕМЕНТУ на ВСЕЙ ОСИ

new_arr = matrix_2d.ravel() # создает копию одномерного массива
new_arr = matrix_2d.view() 
new_arr = matrix_2d.copy() # два вида копий

Допустим у нас есть задача- добавить к существующим 12 фотографиям (shape = (12, 128, 128, 3)) еще одно фото (128, 128, 3). По логичным правилам этого сделать просто так нельзя, что делать? Добавлять новые оси
# Добавление осей

In [6]:
new_arr = np.expand_dims(matrix_2d, axis=0) # добавляет указанную ось
print(new_arr, '\n', matrix_2d, '\n\n\n')

new_arr = matrix_2d[np.newaxis] #добавляет нулевую ось
new_arr = matrix_2d[:, np.newaxis] #добавляет ось на месте первой оси
new_arr = matrix_2d[np.newaxis, :, np.newaxis] #добавили нулевую ось и ось на месте первой оси
new_arr = matrix_2d[:, :, np.newaxis] # \/
new_arr = matrix_2d[..., np.newaxis] #добавляет ось в конце

new_arr = np.squeeze(matrix_2d) # удаляет ось, но только если она имеет не более одного элемента

arr_1, arr_2, arr_3 = np.arange(9).reshape(3,3), np.arange(12).reshape(3, 4), np.arange(15).reshape(3, 5)
arr_h = np.hstack([arr_1, arr_2, arr_3]) # складывает элементы из списка по первой оси ->

arr_1, arr_2, arr_3 = np.arange(9).reshape(3,3), np.arange(12).reshape(4, 3), np.arange(15).reshape(5, 3)
arr_v = np.vstack([arr_1, arr_2, arr_3]) #складывает по нулевой оси \|

arr_1, arr_2 = np.zeros((27, 27, 1)), np.zeros((27, 27, 1))
arr_conca = np.concatenate([arr_1, arr_2], axis=2) #обьединяем массивы по любой оси



#print(arr_h, '\n\n\n')
#print(arr_v, '\n\n\n')
#print(arr_conca.shape)

[[[  0   1]
  [  2   3]
  [  4 100]
  [  6   7]]] 
 [[  0   1]
 [  2   3]
 [  4 100]
 [  6   7]] 





# Разделение осей

In [7]:
arr_1 = np.array([['x_1', 'y_1'], ['x_2', 'y_2'], ['x_3', 'y_3'], ['x_4', 'y_4']])
arr_2 = np.split(arr_1, 2, axis=1) # позволяет разбить матрицу на (указанное число) в (указанной оси)
# разбили исходную матрицу на две части- первая часть с x, вторая с y


#print(arr_1.shape, '\n', arr_1, '\n\n\n')
#print(arr_2)

# Добавление элементов

In [24]:
new_data = np.append(matrix_2d, matrix) # можем указать axis, но по дефолту axis = 0
new_data = np.delete(matrix_2d, 1, axis=1) # удаляем элемент по (указанному индексу) в (указанной оси)

# в качестве индекса можно указывать кортеж (список) индексов, а также срез индексирования
new_data = np.delete(matrix, [1, 2, 3])
new_data = np.delete(matrix, np.s_[::2]) # указывать нужно через np.s_

print(new_data.size)

5


У вас есть задача: к 1000 картинок по очереди добавить еще 1000 картинок. Вместо того что бы использовать циклом метод append, мы можем расширить нашу матрицу методом resize с 1000 до 2000, тогда все остальное место заполнится нулями, и мы как раз начиная с 1000 будем проходиться циклом 1000+i до 2000, и заменять 1000+i = img

In [15]:
%%time

img = np.ones((1000, 28, 28))
img.resize((2000, 28, 28))

for i in range(1000):
    arr = np.random.randint(0, 255, 28*28).reshape([28, 28])
    img[1000+i] = arr

CPU times: total: 0 ns
Wall time: 14.5 ms


# Индексация и срезы
она аналогична индексации в пайтон

In [36]:
print(matrix_3d[0])
print(matrix_3d[0, 1]) # что бы выбрать элемент внутри элемента, нам нужно указывать через запятую [.., ..., ..,] , а не как в пайтон: arr[0][3][1]

matrix_3d[1, 0] = 7 # заменяются все элементы на указанной оси
matrix_3d[0] = [1, 2]

matrix_3d[0:2, 1] = 0 # можно указывать срез нужной оси
matrix_3d[:, 2] # взяли все элементы с конечной оси (:), и 2 ось по индексу
matrix_3d[::2, 1:2]

matrix_3d

[[1 2]
 [0 0]]
[0 0]


array([[[ 1,  2],
        [ 0,  0]],

       [[ 7,  7],
        [ 0,  0]],

       [[99, 99],
        [99, 99]]])

Списочная индексация
(мы считаем переданный кортеж не за обозначение, в какой оси лежит какой то элемент, а считаем все числа в кортеже за индексы, тоесть мы не один элемент берем, а несколько, благодаря кортежу)

In [ ]:
a = matrix_3d[np.arange(3)] # np.arange возвращает три элемента, которые мы принимаем за три индекса
b = matrix_3d[[1, 2], 0]

index = [0, 0, 1, 2, 0]
c = matrix_3d[index]

print(a, '\n\n\n', b, '\n\n\n', c)

# Математические операции

In [53]:
arr = np.random.randint(0, 101, (3, 5))
arr_1 = np.random.randint(1, 11, (3, 5))

print(arr, 'база 1', '\n\n\n')
print(arr_1, 'база 2', '\n\n\n')

arr + 5 # операции с числами выполняются поэлементно

arr + arr_1 # операции с массивами одинакового размера

arr * arr_1 # можно выполнять умножение по элементно, если это СОГЛАСОВАННЫЕ МАССИВЫ (массиввы с одинаковыми размерами)

[[26 20  9 53  8]
 [26 28 74 18 10]
 [51 44 40 71 81]] база 1 



[[ 3  5 10  8  3]
 [ 8  9 10  9  8]
 [ 2  3  5  6  1]] база 2 





array([[ 78, 100,  90, 424,  24],
       [208, 252, 740, 162,  80],
       [102, 132, 200, 426,  81]])

Согласованный или не согласованный массив?

In [54]:
# (2, 3) == (2, 3) <- если shape двух массивов равен, то между ними можно проводить математические операции и операции сравнения 
# (3, 2) != (2, 3)
# (2, 3, 2) != (3, 2)

Если массивы не согласованы, то математические операции все таки можно проводить, благодаря ТРАНСЛИРОВАНИЮ

Правила транслирования:
1. Если массивы имеют разное кол-во осей, то к массиву с меньшим кол-вом осей добавляется (автоматически слева, но можно и самому задать) новая ось, что бы кол-во осей массивов совпали.
2. в массивах на соответствующих осях должно быть либо одинаковое кол-во элементов, либо на оси одной из массивов должен быть лишь 1 элемент 

In [63]:
arr = np.arange(24).reshape(2, 3, 4)
arr_1 = np.arange(8).reshape(2, 4)

arr + arr_1[:, np.newaxis]
# arr_1.shape = (2, 1, 4)
# arr + arr_1

array([[[ 0,  2,  4,  6],
        [ 4,  6,  8, 10],
        [ 8, 10, 12, 14]],

       [[16, 18, 20, 22],
        [20, 22, 24, 26],
        [24, 26, 28, 30]]])

# Математические операции

In [107]:
matrix = np.array([[1., 2.], [3., 4.]])
arr = np.arange(-5, 11, 2)
vector1 = np.arange(10)
vector2 = np.arange(10)

arr.min()
arr.max()
arr.sum()
arr.mean()

np.abs(arr) # возвращает модуль всех элементов массива
# np.log(arr) # подсчитает натуральный логарифм каждого элемента в массиве

np.sin(arr)
np.tan(arr)

# Также, что бы выбрать максимальное значение не по всему массиву, а например, список макс. элементов в подмассивах, то нужно указывать axis
print(matrix_3d.max(axis=1))




# Скалярное произведение векторов
np.dot(vector1, vector2)
vector1 @ vector2
np.inner(vector1, vector2)

# Внешнее прозведение векторов (когда берется первый элемент из первого вектора, и умножается на все элементы второго, потом берется второй вектор и т.д)
np.outer(vector1, vector2)

# Произведение матриц
np.dot(matrix, matrix)
matrix @ matrix
np.matmul(matrix, matrix) # Использовать предпочтительнее

# Элементы линейной алгебры
np.linalg.matrix_rank(matrix_4d)
matrix_1 = np.linalg.inv(matrix) # Обратная матрица- если нам нужна матрица^-1, то эта функция вам в помощь
matrix_T = matrix.T 
# np.transpose(matrix)
np.trace(matrix) # след матрицы
np.linalg.det(matrix) # детерминант, или определитель матрицы (матрица должна быть квадратной)

# Элементы мат статистики
np.median(arr) # Подсчитает медиану в массиве
np.var(arr) # Дисперсия
np.std(arr) # Стандартное отклонение

[[ 1  2]
 [ 7  7]
 [99 99]]


4.58257569495584

Модуль random

In [ ]:
np.random.rand(shape)
# Генерирует массив случайных вещественных чисел в диапазоне [0, 1) с указанной формой. Например, np.random.rand(3, 4) генерирует массив 3x4 случайных чисел между 0 и 1.

np.random.randn(shape)
#Генерирует массив случайных вещественных чисел из нормального распределения (гауссовского распределения) с математическим ожиданием 0 и стандартным отклонением 1. 
# Форма выходного массива определяется входными аргументами. Например, np.random.randn(3, 4) генерирует массив 3x4 случайных чисел из нормального распределения.

np.random.randint(low, high, size)
# Генерирует массив случайных целых чисел в диапазоне [low, high) с указанным размером. Например, np.random.randint(1, 10, 5) генерирует массив 5 случайных целых чисел между 1 и 10.

np.random.normal(loc, scale, size)
# Генерирует массив случайных вещественных чисел из нормального распределения с указанным местоположением (математическим ожиданием), масштабом (стандартным отклонением) и размером.
# Например, np.random.normal(0, 1, 5) генерирует массив 5 случайных чисел из нормального распределения с математическим ожиданием 0 и стандартным отклонением 1.

np.random.permutation(arr/n)
# Возвращает либо перемешанный массив, либо перемешанную последовательность от 0 до n

Методы сравнения

In [102]:
print(matrix_4d[matrix_4d > 10]) # можем сделать выборку, где каждый элемент больше 10

np.all(matrix < 10)
np.any(matrix < 10)

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58
 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82
 83 84 85 86 87 88 89 90 91 92 93 94 95]


True